# Configuration for Sector-Aware Earnings Analyzer
seed: 42
use_lora: false
use_wandb: false
experiment_name: earnings-analyzer
mlflow_tracking_uri: ./mlruns
artifacts_dir: artifacts

# Feature flags
features:
  include_price_features: true
  price_lookback_days: 5
  sector_one_hot: true

# Modeling
model:
  type: logistic_regression  # logistic_regression | random_forest
  logistic_regression:
    C: 1.0
    penalty: l2
    solver: liblinear
    max_iter: 1000
  random_forest:
    n_estimators: 200
    max_depth: 6

# Training
train:
  test_size: 0.25
  val_size: 0.0  # not used in baseline

# Data
paths:
  ticker_sector_map: app/data/ticker_sector_map.csv
  sample_earnings: app/data/sample_earnings.jsonl

# Ingest / external
yfinance_offline: false

# CLI defaults
cli:
  default_ticker: AAPL


